// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTu6aMj1nCZaWcp2AOeqww_CHkl86-jf8',
    appId: '1:976873902024:web:52465c690fae58760cbafd',
    messagingSenderId: '976873902024',
    projectId: 'flutter-edu-715ba',
    authDomain: 'flutter-edu-715ba.firebaseapp.com',
    storageBucket: 'flutter-edu-715ba.appspot.com',
    measurementId: 'G-TQHB92K5Z8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhiXtLNrweyj5pd5noSDBrmsWFzUMS748',
    appId: '1:976873902024:android:488d1cfd1b11c5ad0cbafd',
    messagingSenderId: '976873902024',
    projectId: 'flutter-edu-715ba',
    storageBucket: 'flutter-edu-715ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEMRCi1alPMgD0AmusfmOdKSkIH2GU_pI',
    appId: '1:976873902024:ios:d7a455014a5f3d700cbafd',
    messagingSenderId: '976873902024',
    projectId: 'flutter-edu-715ba',
    storageBucket: 'flutter-edu-715ba.appspot.com',
    iosClientId: '976873902024-2t11po9ppu2a6itlam1l3987dh7eus4p.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseEducation',
  );
}
